# Generated by Django 3.1.7 on 2021-08-25 14:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('sb', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('date', models.DateField(default=datetime.datetime(2021, 8, 25, 16, 55, 19, 24001))),
                ('url', models.CharField(default='', max_length=255)),
                ('user', models.ManyToManyField(blank=True, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rate', models.IntegerField()),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('listing', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.product')),
                ('user', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
