# Generated by Django 3.1.7 on 2021-08-26 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210826_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 26, 14, 32, 0, 958450)),
        ),
    ]
