# Generated by Django 3.1.7 on 2021-09-04 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210904_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 14, 26, 52, 742277)),
        ),
    ]
