# Generated by Django 3.1.7 on 2021-09-09 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210909_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 9, 21, 25, 40, 485961)),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='available', max_length=64),
        ),
    ]
