# Generated by Django 3.1.7 on 2021-12-01 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210909_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='win',
            field=models.CharField(default='not-yet', max_length=64),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 20, 41, 56, 736979)),
        ),
    ]
