# Generated by Django 3.1.7 on 2021-12-01 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20211201_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='winner',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 20, 53, 2, 832815)),
        ),
    ]
