# Generated by Django 3.1.7 on 2021-12-01 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20211201_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 23, 22, 36, 701832)),
        ),
        migrations.AlterField(
            model_name='product',
            name='win',
            field=models.CharField(default=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='winner',
            field=models.CharField(blank='', max_length=64),
        ),
    ]
